baseurl: "https://theinvestorcall.com"
languageCode: "en-us"
title: "The Investor Call"
theme: "hugo-xmag"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: "↩"
hasCJKLanguage: true
enableEmoji: true
paginate: 6

permalinks:
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: Categories
      url: /categories/
      weight: 3
    - name: Tags
      url: /tags/
      weight: 4
    - name: Subscribe
      url: /index.xml

params:
  description: "A bespoke newspaper for the sophisticated investor."
  footer: "&copy; [Sir Zachary R. Merhi and Company,](https://zacmerhi.com) 2017 - 2022 | [Github](https://github.com/zacmando) | [Twitter](https://twitter.com/zacmerhi)"
  github_edit: "https://github.com/yihui/hugo-xmag/edit/master/exampleSite/content/"
  summary_length: 300
  text:
    back: "&larr; Back to Home"
    edit: "Edit this page &rarr;"
    truncated: "&hellip;"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
